# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fn', models.CharField(max_length=64)),
                ('user_ln', models.CharField(max_length=64)),
                ('user_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
